**Name:  Parkar Mihir Rajesh**

**PRN :** 2020033800102674

**Seat No :** 106016

**Email :** mihirparkar2002@gmail.com

**Mobile No:** 8153841347

**SS BE – I (Electronics)**

**Subject :** Programming and Simulation

# **Assignment 9:**




---








**1. Find standard deviation and variance of inputted data using
inbuilt command.**




In [ ]:
import numpy as np
X = [1,3,5,7,2,8]
print("Given Data is : ", X)
STDV = np.std(X)
print("The standard Deviation of Given Data is:",STDV)
V = np.var(X)
print("The variance of Given Data is:", V)

Given Data is :  [1, 3, 5, 7, 2, 8]
The standard Deviation of Given Data is: 2.5603819159562025
The variance of Given Data is: 6.5555555555555545










---






**2. Write a Python code to find the range of inputted data. (max.
value – min. value)**





In [ ]:
import statistics as st

X = [1,3,11,7,6,8,10,17,27,24,38,21]

print("The Given Data:", X)
maxX = max(X)
minX = min(X)
range = maxX - minX

print("The range of the Given Data is:", range)

The Given Data: [1, 3, 11, 7, 6, 8, 10, 17, 27, 24, 38, 21]
The range of the Given Data is: 37
















---











**3. Write a Python code to find the standard deviation and
variance of inputted data. (Discrete series)**





In [ ]:
import statistics as st
import numpy as np

X =np.array([3,2,1,21,12])
F =np.array([1,2,3,4,5,])
Xbar = st.mean(X)
print( "Mean of the Given Data : " ,Xbar)
Y = (X-Xbar)
print(Y)
Y2 = Y*Y*F
print(Y2)
sumY = sum(Y2)
print(sumY)
sumF = sum(F)
print(sumF)
SD = np.sqrt(sumY/sumF)
print("Standard Deviation :",SD)
Var = SD*SD
print("The Variance Of the Data:",Var)

Mean of the Given Data :  7
[-4 -5 -6 14  5]
[ 16  50 108 784 125]
1083
15
Standard Deviation : 8.497058314499201
The Variance Of the Data: 72.2












---










**4. Write a Python code to find the standard deviation and
variance of inputted data. (Continuous series)**





In [ ]:
import numpy as np
import statistics as st

UL = np.array([10,20,30,40,50,60])
LL = np.array([20,30,40,50,60,70])
f = np.array([4,7,16,20,15,8])
ML = UL+LL/2
print(ML)
MLbar = st.mean(ML)
print("Mean of the Data : ",MLbar)
Y = (MLbar)
Y2 = Y*Y*f
print(Y2)


sumY = sum(Y2)
print(sumY)
sumf = sum(f)
print("Total Frequency : ",sumf)
SD = np.sqrt(sumY/sumf)
print("The standard Deviation Of the Data : ", SD)
VAR = SD * SD
print("The Variance Of the Data : ", VAR)

[20. 35. 50. 65. 80. 95.]
Mean of the Data :  57.5
[13225.   23143.75 52900.   66125.   49593.75 26450.  ]
231437.5
Total Frequency :  70
The standard Deviation Of the Data :  57.5
The Variance Of the Data :  3306.25











---





