# NumPy_Numarical Pyuthon Library

In [1]:
#Importing Numpy
import numpy as np


In [10]:
#create simple array
#single line array
arr1=np.array([1,2,3])

#n * m Array
arr2=np.array([[1,2,3],[4,5,6]]) #n=3,m=2

print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [20]:
#how to access elements
print(arr1[0])
print(arr2[1][2])

#Dimensions
print(arr1.ndim) 
print(arr2.ndim) 

#Order of the Array
print(arr1.shape) 
print(arr2.shape)

#Memory data Location
print(arr2.data)

#length
print(arr2.size)

#Type
print(type(arr1))

1
6
1
2
(3,)
(2, 3)
6
<class 'numpy.ndarray'>


# LAB1
# RANDOM NUMBER GENERATOR

In [5]:
#import randome module from numpy
from numpy import random 
x=random.rand(5)
print(x)

y=random.randint(100,size=3)
print(y)

z=random.randint(100,size=(3,3))
print(z)

[0.78189371 0.22673792 0.9835255  0.95107539 0.34903997]
[93 11 25]
[[44 91 57]
 [16 79 73]
 [46 12 67]]


In [6]:
#random integer
a=random.randint((2,2))
print(a)
#Float
b=random.random((2,2))
print(b)

[1 1]
[[0.04131918 0.83348217]
 [0.42713266 0.50896072]]


 z=random.randint(10,size=(3,3))
random.seed(10)
print(z)

# Numpy Matrix functions

In [15]:
#Different types of Matrix

#Zero matrix
zero = np.zeros((3,3))
print(zero)
print()

#Ones Matrix
one = np.ones((3,3))
print(one)
print()

#identity matrix
idt = np.eye((3))
print(idt)
print()

#constant
const = np.full((3,3),5)
print(const)
print()


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[5 5 5]
 [5 5 5]
 [5 5 5]]



In [33]:
#Operations with matrixsy
print(7*idt)

[[7. 0. 0.]
 [0. 7. 0.]
 [0. 0. 7.]]


# Array Indexing and Slicing

In [36]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
#access
print(arr[0][0],arr[1][1],arr[2][2])

#replace

print(arr)
arr[2][3] = 1
print(arr)

1 6 11
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  1]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  1]]


In [49]:
#Slicing
#arr[slicing of rows,slicing of cols]
#arr[st:end,st:end]

print(arr)
print()

arr1=arr[1: , 1:3]
print(arr1)
print()

narr = arr[1:3,1:4]

print(narr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  1]]

[[ 6  7]
 [10 11]]

[[ 6  7  8]
 [10 11  1]]


In [50]:
arr1 = np.full((3,4),2)
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# Array Broadcasting

In [70]:
print(arr)
print()
print(arr1)
print()


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  1]]

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]



In [69]:
#Addition
print(arr1+arr,"\n")

addition = np.add(arr,arr1)

print(addition)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13  3]] 

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13  3]]


In [68]:
#subtraction
sub = np.subtract(arr,arr1)
print(sub)

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 -1]]


In [65]:
#multiplication
print(arr*arr1)
print(np.multiply(arr,arr1))

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22  2]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22  2]]


In [66]:
#Square root
sq = np.sqrt(arr1)
print(sq)

[[1.41421356 1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356 1.41421356]]


In [74]:
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [71]:
#sum
np.sum(arr1)

24

In [72]:
np.sum(arr1,axis=0)

array([6, 6, 6, 6])

In [73]:
np.sum(arr1,axis=1)

array([8, 8, 8])

In [75]:
np.sum(arr1[0])

8

# Calculate BMI of Players

In [85]:
#Heights of Player 

height_in = [67,62,73,68,69,61,71,70,67,70,63]

ht_np = np.array(height_in)
print(ht_np)

#Convert inch to meter
hm = ht_np*0.0245
print(hm)

[67 62 73 68 69 61 71 70 67 70 63]
[1.6415 1.519  1.7885 1.666  1.6905 1.4945 1.7395 1.715  1.6415 1.715
 1.5435]


In [81]:
#Weights of Player

w = [100,120,111,121,106,103,113,101,115,107,109]
wa=np.array(w)
print(wa)

#Convert into kg
wkg = wa*0.45
print(wkg)


[100 120 111 121 106 103 113 101 115 107 109]
[45.   54.   49.95 54.45 47.7  46.35 50.85 45.45 51.75 48.15 49.05]


In [86]:
#Calculate BMI

bmi = wkg/hm**2
print(bmi)

[16.70054868 23.40335994 15.61556145 19.61769101 16.69121798 20.75190161
 16.80513831 15.45274503 19.20563098 16.37072988 20.58854918]


In [88]:
bmi[bmi>20]

array([23.40335994, 20.75190161, 20.58854918])

In [90]:
players = np.array[(wkg,hm)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [92]:
arr1T= arr1.T
print(arr1T)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


# Statastical Operations

In [ ]:
#max,min,avg,var,std,etc...

# Boolean Operations

In [5]:
bools = [False,True,True,True,False]
bools
ba = np.array(bools)
ba

array([False,  True,  True,  True, False])

In [6]:
ba.sum()

3

In [7]:
ba.any()

True

In [8]:
ba.all()

False

In [10]:
n = np.array(['a','b','c','d','a','b'])
n

array(['a', 'b', 'c', 'd', 'a', 'b'], dtype='<U1')

In [11]:
np.unique(n)

array(['a', 'b', 'c', 'd'], dtype='<U1')